## Spotify analysis part2: technically advanced for learning

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df=pd.read_excel("/Users/ananyatalukdar/Documents/dataScience_self/spotify user analysis/data/raw/Spotify_data.xlsx")
df.head()

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating,pod_lis_frequency,fav_pod_genre,preffered_pod_format,pod_host_preference,preffered_pod_duration,pod_variety_satisfaction
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [4]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          520 non-null    object
 1   Gender                       520 non-null    object
 2   spotify_usage_period         520 non-null    object
 3   spotify_listening_device     520 non-null    object
 4   spotify_subscription_plan    520 non-null    object
 5   premium_sub_willingness      520 non-null    object
 6   preffered_premium_plan       312 non-null    object
 7   preferred_listening_content  520 non-null    object
 8   fav_music_genre              520 non-null    object
 9   music_time_slot              520 non-null    object
 10  music_Influencial_mood       520 non-null    object
 11  music_lis_frequency          520 non-null    object
 12  music_expl_method            520 non-null    object
 13  music_recc_rating            520 non-null    int64
 14  pod_lis_frequency            520 non-null    object
 15  fav_pod_genre                372 non-null    object
 16  preffered_pod_format         380 non-null    object
 17  pod_host_preference          379 non-null    object
 18  preffered_pod_duration       391 non-null    object
 19  pod_variety_satisfaction     520 non-null    object
dtypes: int64(1), object(19)
memory usage: 81.4+ KB
None
       music_recc_rating
count         520.000000
mean            3.503846
std             0.979552
min             1.000000
25%             3.000000
50%             3.500000
75%             4.000000
max             5.000000
Age                              0
Gender                           0
spotify_usage_period             0
spotify_listening_device         0
spotify_subscription_plan        0
premium_sub_willingness          0
preffered_premium_plan         208
preferred_listening_content      0
fav_music_genre                  0
music_time_slot                  0
music_Influencial_mood           0
music_lis_frequency              0
music_expl_method                0
music_recc_rating                0
pod_lis_frequency                0
fav_pod_genre                  148
preffered_pod_format           140
pod_host_preference            141
preffered_pod_duration         129
pod_variety_satisfaction         0
dtype: int64

In [5]:
for c in df.columns:
    print(str(df[c].value_counts(dropna=False))+"\n")

Age
20-35    422
12-20     71
35-60     23
6-12       3
60+        1
Name: count, dtype: int64

Gender
Female    391
Male      114
Others     15
Name: count, dtype: int64

spotify_usage_period
More than 2 years     169
1 year to 2 years     141
6 months to 1 year    119
Less than 6 months     91
Name: count, dtype: int64

spotify_listening_device
Smartphone                                                                              300
Computer or laptop                                                                       54
Smartphone, Computer or laptop                                                           48
Smart speakers or voice assistants                                                       43
Computer or laptop, Smart speakers or voice assistants                                   14
Smartphone, Smart speakers or voice assistants                                           10
Smartphone, Wearable devices                                                              8
Smartphone, Computer or laptop, Smart speakers or voice assistants, Wearable devices      8
Wearable devices                                                                          8
Smartphone, Computer or laptop, Smart speakers or voice assistants                        7
Smartphone, Computer or laptop, Wearable devices                                          5
Computer or laptop, Wearable devices                                                      5
Smartphone, Smart speakers or voice assistants, Wearable devices                          5
Computer or laptop, Smart speakers or voice assistants, Wearable devices                  3
Smart speakers or voice assistants, Wearable devices                                      2
Name: count, dtype: int64

spotify_subscription_plan
Free (ad-supported)            424
Premium (paid subscription)     96
Name: count, dtype: int64

premium_sub_willingness
No     334
Yes    186
Name: count, dtype: int64

preffered_premium_plan
NaN                               208
Individual Plan- Rs 119/ month     95
Student Plan-Rs 59/month           94
Duo plan- Rs 149/month             84
Family Plan-Rs 179/month           39
Name: count, dtype: int64

preferred_listening_content
Music      410
Podcast    110
Name: count, dtype: int64

fav_music_genre
Melody                       259
classical                     87
Pop                           85
Rap                           55
Electronic/Dance              16
All                            6
Rock                           4
Kpop                           4
Classical & melody, dance      2
Old songs                      1
trending songs random          1
Name: count, dtype: int64

music_time_slot
Night        312
Afternoon    117
Morning       91
Name: count, dtype: int64

music_Influencial_mood
Relaxation and stress relief                                                                                     195
Uplifting and motivational                                                                                        67
Sadness or melancholy                                                                                             55
Relaxation and stress relief, Uplifting and motivational                                                          44
Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy, Social gatherings or parties     35
Relaxation and stress relief, Sadness or melancholy                                                               33
Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy                                   22
Social gatherings or parties                                                                                      16
Relaxation and stress relief, Uplifting and motivational, Social gatherings or parties                            14
Relaxation and stress relief, Social gatherings or parties                                                        13
Uplifting and motivational, Sadness or melancholy                                                                 12
Relaxation and stress relief, Sadness or melancholy, Social gatherings or parties                                  8
Uplifting and motivational, Social gatherings or parties                                                           4
Sadness or melancholy, Social gatherings or parties                                                                1
Uplifting and motivational, Sadness or melancholy, Social gatherings or parties                                    1
Name: count, dtype: int64

music_lis_frequency
While Traveling                                                                111
leisure time                                                                    87
While Traveling, leisure time                                                   65
While Traveling, Workout session, leisure time                                  48
Workout session                                                                 33
Study Hours                                                                     19
Office hours                                                                    16
While Traveling, Workout session                                                16
Office hours, While Traveling                                                   12
Office hours, While Traveling, leisure time                                     12
Office hours, While Traveling, Workout session                                  10
Study Hours, While Traveling, leisure time                                      10
Study Hours, While Traveling                                                     9
Office hours, Study Hours, While Traveling, Workout session, leisure time        7
Study Hours, While Traveling, Workout session                                    7
Office hours, Study Hours, While Traveling                                       7
Study Hours, Workout session                                                     6
Office hours, leisure time                                                       6
Workout session, leisure time                                                    6
Study Hours, While Traveling, Workout session, leisure time                      4
Study Hours, Workout session, leisure time                                       4
Study Hours, leisure time                                                        4
Office hours, While Traveling, Workout session, leisure time                     3
Office hours, Study Hours, While Traveling, leisure time                         3
Office hours, Workout session                                                    3
Office hours, While Traveling,                                                   2
Office hours, Study Hours, Workout session                                       2
While Traveling, Workout session, leisure time, Night time, when cooking         1
Social gatherings                                                                1
Random                                                                           1
Office hours, Workout session, leisure time                                      1
While Traveling, Before bed                                                      1
Office hours, Study Hours, While Traveling, Workout session                      1
Office hours, Study Hours, While Traveling, Workout session, leisure time,       1
Office hours,Study Hours, While Traveling, leisure time                          1
Name: count, dtype: int64

music_expl_method
recommendations                              113
Playlists                                    112
recommendations, Playlists                    86
Others                                        55
Radio                                         51
Playlists, Radio                              18
recommendations, Playlists, Others            18
recommendations, Others                       15
recommendations, Playlists, Radio             13
Playlists, Others                              9
Radio, Others                                  7
recommendations, Radio                         6
Playlists, Radio, Others                       6
recommendations, Radio, Others                 4
recommendations, Playlists, Radio, Others      2
recommendations,Others, Social media           1
Others, Social media                           1
Others, Friends                                1
recommendations, Others, Social media          1
Others, Search                                 1
Name: count, dtype: int64

music_recc_rating
3    190
4    174
5     86
2     56
1     14
Name: count, dtype: int64

pod_lis_frequency
Rarely                  201
Never                   130
Once a week              91
Several times a week     78
Daily                    20
Name: count, dtype: int64

fav_pod_genre
NaN                                                 148
Comedy                                              107
Lifestyle and Health                                102
Health and Fitness                                   78
Sports                                               51
Food and cooking                                     20
Finance related and current affairs                   1
Educational                                           1
Self help                                             1
Novels                                                1
Political, informative, topics that interests me      1
Murder Mystery                                        1
Technology                                            1
Spiritual and devotional                              1
General knowledge                                     1
Dance and Relevant cases                              1
Informative stuff                                     1
Everything                                            1
Business                                              1
Stories                                               1
Name: count, dtype: int64

preffered_pod_format
Story telling     152
NaN               140
Conversational    105
Interview          74
Educational        49
Name: count, dtype: int64

pod_host_preference
Both                      180
NaN                       141
Well known individuals    114
unknown Podcasters         85
Name: count, dtype: int64

preffered_pod_duration
Shorter    191
NaN        129
Both       117
Longer      83
Name: count, dtype: int64

pod_variety_satisfaction
Ok                   280
Satisfied            162
Very Satisfied        48
Dissatisfied          20
Very Dissatisfied     10
Name: count, dtype: int64

In [7]:
df.duplicated().sum()
df = df.drop_duplicates()

In [13]:
multi_select_cols = [
    'spotify_listening_device', 
    'music_Influencial_mood', 
    'music_lis_frequency', 
    'music_expl_method'
]

def expand_multi_select(df, column):
    expanded = df[column].str.get_dummies(sep=', ')
    expanded = expanded.add_prefix(f"{column}_")
    return expanded

expanded_df = pd.DataFrame(index=df.index)

for c in multi_select_cols:
    expanded_feature = expand_multi_select(df,c)
    expanded_df = pd.concat([expanded_df, expanded_feature], axis=1)

expanded_df.head()

,spotify_listening_device_Computer or laptop,spotify_listening_device_Smart speakers or voice assistants,spotify_listening_device_Smartphone,spotify_listening_device_Wearable devices,music_Influencial_mood_Relaxation and stress relief,music_Influencial_mood_Sadness or melancholy,music_Influencial_mood_Social gatherings or parties,music_Influencial_mood_Uplifting and motivational,music_lis_frequency_Before bed,music_lis_frequency_Night time,...,music_lis_frequency_leisure time,music_lis_frequency_when cooking,music_expl_method_Friends,music_expl_method_Others,music_expl_method_Playlists,music_expl_method_Radio,music_expl_method_Search,music_expl_method_Social media,music_expl_method_recommendations,"music_expl_method_recommendations,Others"
0,0,1,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
1,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,1,1,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
4,0,0,1,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0